### ISSUE TITLE
I can't build apk

### ISSUE THREAD

**Issue by cakircan-cakir** [bmshifat/TecSpy#5]
Hello there. I installed this program on my server on amazon and it worked without any problems, but I could not find the builder. I am attaching an example image.
![Ekran görüntüsü 2021-06-11 192241](https://user-images.githubusercontent.com/57761847/121717927-6aece480-caea-11eb-928b-341b238fd435.png)
Anyway, when I changed the url to /builder, the builder screen came up. I am attaching an example image.
![Ekran görüntüsü 2021-06-11 192459](https://user-images.githubusercontent.com/57761847/121718212-bacbab80-caea-11eb-9c57-97f7efd9a570.png)
But when I click on any download link on this screen, it redirects me to a non-existent site. So I can't download apk. I'm adding the url addresses it redirects to.
http://tecarticle.com/.app/TecSpy(WithAdmin).apk
http://tecarticle.com/.app/TecSpy(WithoutAdmin).apk
Please fix this

**Comment by moviely** [comment]
sorry to say i have removed the app i can give you the app source code you have to build it by your self

**Comment by bmshifat** [comment]
sorry to say I have removed the app I can give you the app source code you have to build it by yourself, please mail me on this shifat8m@gmail.com
